default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: stomping-ground_development

test:
  <<: *default
  database: stomping-ground_test

production:
  <<: *default
  database: stomping-ground_production
  username: stoming-ground
  password: <%= ENV['STOMPING-GROUND_DATABASE_PASSWORD']%>
